name: piqueserver
base: core18 
version: "latest"
summary: piqueserver
description: |
  An Ace of Spades 0.75 server based on PySnip

grade: stable
confinement: strict

parts:
  piqueserver:
    plugin: python
    python-packages: [piqueserver]
    build-packages:
      - build-essential
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - libjpeg-dev
  launcher:
    plugin: dump
    source: snap/local

apps:
  piqueserver:
    command: launcher
    daemon: simple
    plugs:
      - network
      - network-bind
