name: piqueserver
base: core22
adopt-info: piqueserver
summary: piqueserver
description: |
  An Ace of Spades 0.75 server based on PySnip
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: i386
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el
grade: stable
confinement: strict

parts:
  piqueserver:
    plugin: python
    python-packages: [requests>=2.28.0, jellyfish>=0.9.0]
    source: https://github.com/piqueserver/piqueserver.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git rev-parse --short HEAD)"
    build-packages:
      - build-essential
      - libenet-dev
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - libjpeg-dev
      - rustc
      - cargo      
    # override-build: |
    #   snapcraftctl build
    #   snapcraftctl set-version "$(pip3 show piqueserver | grep '^Version' | awk -F ' ' '{ print $2 }')"
  launcher:
    plugin: dump
    source: snap/local

apps:
  piqueserver:
    command: bin/launcher
    daemon: simple
    plugs:
      - network
      - network-bind

