name: piqueserver
base: core20
adopt-info: piqueserver
summary: piqueserver
description: |
  An Ace of Spades 0.75 server based on PySnip

grade: stable
confinement: strict

parts:
  piqueserver:
    plugin: python
    #python-packages: [piqueserver==1.0.0]
    source: https://github.com/piqueserver/piqueserver.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git rev-parse --short HEAD)"
    build-packages:
      - build-essential
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - libjpeg-dev
    # override-build: |
    #   snapcraftctl build
    #   snapcraftctl set-version "$(pip3 show piqueserver | grep '^Version' | awk -F ' ' '{ print $2 }')"
  launcher:
    plugin: dump
    source: snap/local

apps:
  piqueserver:
    command: bin/launcher
    daemon: simple
    plugs:
      - network
      - network-bind

