name: piqueserver
base: core18 
version: "latest"
summary: piqueserver
description: |
  An Ace of Spades 0.75 server based on PySnip

grade: stable
confinement: strict

parts:
  build-trigger:
    source: https://github.com/piqueserver/piqueserver.git
    plugin: nil
  piqueserver:
    plugin: python
    python-packages: [piqueserver]
    build-packages:
      - build-essential
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - libjpeg-dev
    # override-build: |
    #   snapcraftctl build
    #   snapcraftctl set-version "$(pip3 show piqueserver | grep '^Version' | awk -F ' ' '{ print $2 }')"
  launcher:
    plugin: dump
    source: snap/local

apps:
  piqueserver:
    command: launcher
    daemon: simple
    plugs:
      - network
      - network-bind
